sonar.projectKey=remi-and-nneoma
sonar.projectName=Remi and Nneoma
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/*.mp4,**/*.mp3,**/*.jpg,**/*.jpeg,**/*.png,**/*.gif,**/*.webp,**/*.svg,**/*.woff,**/*.woff2,**/*.ttf,**/*.eot

# Optional
sonar.scm.provider=git
