name: Build Scan and Deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  IMAGE_NAME: remi-and-nneoma

jobs:

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: echo "Deploying"
